version: 0.0
os: linux
files:
  - source: /testjar/SecureTomcatJDBC-test.jar
    destination: /home/ec2-user/test/
    overwrite: true
file_exists_behavior: OVERWRITE
#hooks:
  #BeforeInstall:
    #- location: script/backup_and_delete.sh
      #timeout: 300
      #runas: root
branch_config:
    wip\/.*: ~ 
    main:
        deploymentGroupName: RIDA_TST_GROUP
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::776543442213:role/RIDA_CODEDEPLOY_ROLE
# Updated on Mon Feb 24 14:07:03 UTC 2025
