version: 0.0
os: linux
files:
  - source: Addition.jar
    destination: /home/ec2-user/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
file_exists_behavior: OVERWRITE
branch_config:
  wip\/.*: ~ 
  main:
    deploymentGroupName: RIDA_DEV_GROUP
    deploymentGroupConfig:
      serviceRoleArn: arn:aws:iam::776543442213:role/RIDA_CODEDEPLOY_ROLE
            
