version: 0.0
os: linux
files:
  - source: /devjar/SecureTomcatJDBC-dev.jar
    destination: /home/ec2-user/
    overwrite: true
branch_config:
  wip\/.*: ~ 
  main:
    deploymentGroupName: RIDA_DEV_GROUP
    deploymentGroupConfig:
      serviceRoleArn: arn:aws:iam::776543442213:role/RIDA_CODEDEPLOY_ROLE
            
# Updated on Fri Feb  7 12:42:43 UTC 2025
