
name: Java CI with Ant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -f build.xml jar

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: addition-jar
        path: dist/lib/Addition.jar

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build # Ensure the deployment job waits for the build job to complete
    environment:
      name: Dev
      url: gdbdev.gilead.com
      
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    #- name: Copy AppSpec File for Dev
      #run: cp appspec-dev.yml appspec.yml 
      
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
        aws-region: us-west-2
    
    - name: Create Code Deploy
      id: deploy-dev
      uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
      with:
        application: RIDA_DEV
        appspec-file: appspec.yml
        #serviceRoleArn: 

    - name: Print Commit Message
      uses: peter-evans/commit-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=us-east-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.

  deploy-tst:
    runs-on: ubuntu-latest
    needs: deploy-dev  # Ensure deploy-prod waits for deploy-dev to finish
  
    environment:
      name: Test
      url: gdbtst.gilead.com  
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy AppSpec File for Tst
      run: cp appspec-tst.yml appspec.yml
      
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::099269900176:role/OpenIDConnectRoleRIDA
        aws-region: ap-south-1
    
    - name: Create Code Deploy
      id: deploy-tst
      uses: webfactory/create-aws-codedeploy-deployment@v0.4.0  # Use the appropriate version
      with:
        application: GithubActionsXCodedeploy
        appspec-file: appspec.yml
        #serviceRoleArn: arn:aws:iam::099269900176:role/CodedeployCustomRole

    - name: Print Commit Message
      uses: peter-evans/commit-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          @${{ github.actor }} this was deployed as ${{ steps.deploy.outputs.deploymentId }} to group `${{ steps.deploy.outputs.deploymentGroupName }}`.

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-tst  # Ensure deploy-prod waits for deploy-dev to finish
  
    environment:
      name: Prod
      url: gdb.gilead.com   
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy AppSpec File for Prod
      run: cp appspec-prod.yml appspec.yml
      
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::099269900176:role/OpenIDConnectRoleRIDA
        aws-region: ap-south-1
    
    - name: Create Code Deploy
      id: deploy-prd
      uses: webfactory/create-aws-codedeploy-deployment@v0.4.0  # Use the appropriate version
      with:
        application: GithubActionsXCodedeploy
        appspec-file: appspec.yml
        #serviceRoleArn: arn:aws:iam::099269900176:role/CodedeployCustomRole

    - name: Print Commit Message
      uses: peter-evans/commit-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          @${{ github.actor }} this was deployed as ${{ steps.deploy.outputs.deploymentId }} to group `${{ steps.deploy.outputs.deploymentGroupName }}`.
     
   
