name: Java CI with Ant

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        
      - name: Build with Ant
        run: ant -f build.xml jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: addition-jar
          path: dist/lib/Addition.jar

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory
        run: ls -al 
      
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam:::role/OpenIDConnectRole
          aws-region: ap-south-1
    
      - name: Create Code Deploy
        id: deploy
        uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
        with:
          application: GithubActionsXCodedeploy
          #serviceRoleArn: 

      - name: Print Commit Message
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.actor }} this was deployed as [${{ steps.deploy.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy.outputs.deploymentId }}?region=us-east-1) to group `${{ steps.deploy.outputs.deploymentGroupName }}`.

  approval-test:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: test
      reviewers:
        - username1
    steps:
      - name: Await Approval
        run: echo "Awaiting manual approval from username1..."
        env:
          DEPLOYMENT_STATUS: "approved"
          DEPLOYMENT_APPROVER: ${{ github.actor }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: approval-test
    environment:
      name: test
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory
        run: ls -al 

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::099269900176:role/OpenIDConnectRoleRIDA
          aws-region: ap-south-1
    
      - name: Create Code Deploy for Test
        id: deploy-test
        uses: webfactory/create-aws-codedeploy-deployment@v1.0.2
        with:
          application: TSTAPP
          deployment-group: TSTGroup
          #serviceRoleArn: 

      - name: Print Commit Message for Test
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.actor }} this was deployed as [${{ steps.deploy-test.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy-test.outputs.deploymentId }}?region=us-east-1) to group `${{ steps.deploy-test.outputs.deploymentGroupName }}`.

  approval-prod:
    runs-on: ubuntu-latest
    needs: deploy-test
    environment:
      name: prod
      reviewers:
        - username2
    steps:
      - name: Await Approval
        run: echo "Awaiting manual approval from username2..."
        env:
          DEPLOYMENT_STATUS: "approved"
          DEPLOYMENT_APPROVER: ${{ github.actor }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: approval-prod
    environment:
      name: prod
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory
        run: ls -al 

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam:::role/OpenIDConnectRole
          aws-region: ap-south-1
    
      - name: Create Code Deploy for Prod
        id: deploy-prod
        uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
        with:
          application: ProdApp
          deployment-group: ProdGroup
          #serviceRoleArn: 

      - name: Print Commit Message for Prod
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            @${{ github.actor }} this was deployed as [${{ steps.deploy-prod.outputs.deploymentId }}](https://console.aws.amazon.com/codesuite/codedeploy/deployments/${{ steps.deploy-prod.outputs.deploymentId }}?region=us-east-1) to group `${{ steps.deploy-prod.outputs.deploymentGroupName }}`.
