name: Build, Upload, and Commit Artifact

on:
  push:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set the permissions for GITHUB_TOKEN
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Ant for Dev
      run: ant -f build.xml -Djar.name=SecureTomcatJDBC-dev.jar -propertyfile build-dev.properties jar

    - name: Upload Artifact for Dev
      uses: actions/upload-artifact@v4
      with:
        name: securetomcatjdbc-dev-jar
        path: dist/SecureTomcatJDBC-dev.jar

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull latest changes
      run: git pull origin main

    - name: Commit JAR for Dev
      run: |
        mkdir -p devjar
        mv dist/SecureTomcatJDBC-dev.jar devjar/
        git add devjar/SecureTomcatJDBC-dev.jar
        git commit -m "Add SecureTomcatJDBC-dev.jar artifact"
        git push origin main

  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set the permissions for GITHUB_TOKEN
    needs: build-dev
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Ant for Test
      run: ant -f build.xml -Djar.name=SecureTomcatJDBC-test.jar -propertyfile build-test.properties jar

    - name: Upload Artifact for Test
      uses: actions/upload-artifact@v4
      with:
        name: securetomcatjdbc-test-jar
        path: dist/SecureTomcatJDBC-test.jar

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull latest changes
      run: git pull origin main

    - name: Commit JAR for Test
      run: |
        mkdir -p testjar
        mv dist/SecureTomcatJDBC-test.jar testjar/
        git add testjar/SecureTomcatJDBC-test.jar
        git commit -m "Add SecureTomcatJDBC-test.jar artifact"
        git push origin main

  build-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set the permissions for GITHUB_TOKEN
    needs: build-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Ant for Prod
      run: ant -f build.xml -Djar.name=SecureTomcatJDBC-prod.jar -propertyfile build-prod.properties jar

    - name: Upload Artifact for Prod
      uses: actions/upload-artifact@v4
      with:
        name: securetomcatjdbc-prod-jar
        path: dist/SecureTomcatJDBC-prod.jar

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull latest changes
      run: git pull origin main

    - name: Commit JAR for Prod
      run: |
        mkdir -p prodjar
        mv dist/SecureTomcatJDBC-prod.jar prodjar/
        git add prodjar/SecureTomcatJDBC-prod.jar
        git commit -m "Add SecureTomcatJDBC-prod.jar artifact"
        git push origin main
