name: Build, Upload, and Commit Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set the permissions for GITHUB_TOKEN
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Ant
      run: ant -f build.xml jar

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: addition-jar
        path: Addition.jar

    - name: List files in root directory
      run: ls -la

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit Addition JAR
      run: |
        echo "Listing files before git add..."
        ls -la  # List files to confirm Addition.jar is present
        if [ -f Addition.jar ]; then
          git add Addition.jar
          git commit -m "Add Addition.jar artifact"
          git push origin main
        else
          echo "Error: Addition.jar not found in the root directory."
          exit 1
        fi

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
  
    environment:
      name: Dev
      url: https://gdbdev.gilead.com  
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Copy AppSpec File for Dev
      run: |
        cp appspec-dev.yml appspec.yml
        ls -la  # Verify the file is copied

    - name: Configure Git
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull Latest Changes
      run: git pull origin main

    - name: Commit and Push AppSpec File
      run: |
         echo "Listing files before git add..."
         ls -la  # List files to confirm appspec.yml is present
         
         if [ -f appspec.yml ]; then
           git add appspec.yml
           git commit -m "Update appspec.yml file for Dev" --allow-empty
           git push origin main
         else
           echo "Error: appspec.yml not found in the root directory."
           exit 1 
         fi


    - name: List files
      run: ls -la
      
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
        aws-region: us-west-2

    - name: Create Code Deploy
      id: deploy-dev
      uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
      with:
        application: RIDA_DEV
        appspec-file: appspec.yml

    - name: Print Commit Message
      uses: peter-evans/commit-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          @${{ github.actor }} this was deployed as ${{ steps.deploy-dev.outputs.deploymentId }} to group `${{ steps.deploy-dev.outputs.deploymentGroupName }}`.

  deploy-Tst:
    runs-on: ubuntu-latest
    needs: deploy-dev
  
    environment:
      name: Test
      url: https://gdbtst.gilead.com  
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy AppSpec File for Tst
      run: |
        cp appspec-tst.yml appspec.yml
        ls -la  # Verify the file is copied

    - name: Configure Git
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull Latest Changes
      run: git pull origin main

    - name: Commit and Push AppSpec File
      run: |
         echo "Listing files before git add..."
         ls -la  # List files to confirm appspec.yml is present
         
         if [ -f appspec.yml ]; then
           git add appspec.yml
           git commit -m "Update appspec.yml file for Tst" --allow-empty
           git push origin main
         else
           echo "Error: appspec.yml not found in the root directory."
           exit 1 
         fi

    - name: List files
      run: ls -la
      
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
        aws-region: us-west-2

    - name: Create Code Deploy
      id: deploy-tst
      uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
      with:
        application: RIDA_TST
        appspec-file: appspec.yml

    - name: Print Commit Message
      uses: peter-evans/commit-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          @${{ github.actor }} this was deployed as ${{ steps.deploy-dev.outputs.deploymentId }} to group `${{ steps.deploy-dev.outputs.deploymentGroupName }}`.
