name: Build & Deploy for Test env

on:
  workflow_run:
    workflows: ['Dev-CI.yaml']
    types: [completed]

jobs:
  build-tst:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly set the permissions for GITHUB_TOKEN
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Ant for Test
      run: ant -f build.xml -Djar.name=SecureTomcatJDBC-tst.jar -propertyfile build-test.properties jar

    - name: Upload Artifact for Test
      uses: actions/upload-artifact@v4
      with:
        name: securetomcatjdbc-tst-jar
        path: dist/SecureTomcatJDBC-tst.jar

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Pull latest changes
      run: git pull origin main

    - name: Commit JAR for Test
      run: |
        mkdir -p tstjar
        mv dist/SecureTomcatJDBC-tst.jar tstjar/
        git add tstjar/SecureTomcatJDBC-tst.jar
        git commit -m "Add SecureTomcatJDBC-tst.jar artifact"
        git push origin main

  push-appspec-tst-yml:
    runs-on: ubuntu-latest
    needs: build-tst
  
    environment:
      name: Test
      url: https://gdbtst.gilead.com  
    permissions:
      id-token: write
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Copy AppSpec File for Test
      run: |
        cp appspec-test.yml appspec.yml
        ls -la  # Verify the file is copied
    - name: Configure Git
      run: |
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Pull Latest Changes
      run: |
         git stash
         git pull origin main || true
         git stash pop
         git add appspec.yml
         git commit -m "Update appspec.yml" || echo "No changes to commit"
         git push origin main || true

    - name: Resolve Merge Conflicts
      if: failure()
      run: |
         git merge --strategy-option theirs
         git add appspec.yml
         git commit -m "Resolved merge conflict in appspec.yml"
         git push origin main

    - name: Commit and Push AppSpec File
      run: |
         echo "Listing files before git add..."
         ls -la  # List files to confirm appspec.yml is present
    
         if [ -f appspec.yml ]; then
            echo "# Updated on $(date)" >> appspec.yml  # Append a comment with the current date and time
            git add appspec.yml
            git commit -m "Update appspec.yml file for Test" || echo "No changes to commit"
            git push origin main
         else
            echo "Error: appspec.yml not found in the root directory."
            exit 1 
         fi
         
    - name: List files
      run: ls -la
  
  deploy-tst:
    runs-on: ubuntu-latest
    needs: push-appspec-tst-yml
    environment:
      name: Test
      url: https://gdbtst.gilead.com
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::776543442213:role/RIDA_AWS_OIDC_CODEDEPLOY_ROLE
        aws-region: us-west-2
    - name: Create Code Deploy
      id: deploy-tst
      uses: webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
      with:
        application: RIDA_TST
    - name: Retry Deployment on Failure
      if: failure()
      run: |
        for i in {1..3}; do
          echo "Attempt $i: Retrying deployment..."
          sleep 30  # Wait for 30 seconds before retrying
          webfactory/create-aws-codedeploy-deployment/create-deployment@v0.5.0
          with:
            application: RIDA_TST
          if [ $? -eq 0 ]; then
            echo "Deployment succeeded on attempt $i"
            break
          fi
        done
    - name: Print Commit Message
      uses: peter-evans/commit-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: >
          @${{ github.actor }} this was deployed as ${{
          steps.deploy-tst.outputs.deploymentId }} to group `${{
          steps.deploy-tst.outputs.deploymentGroupName }}`.
